server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/currency_exchange
    username: postgres
    password: postgres

rate-source:
  url: https://openexchangerates.org/api
  api-key: ${API_KEY}
  delay: 30000 #n